server:
  port: ${PORT:8081}

spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      fail-on-empty-beans: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://herwaycabs-discovery.onrender.com/eureka}

  instance:
    prefer-ip-address: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

info:
  build:
    marker: auth-antpath-fix-v1

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

logging:
  level:
    root: INFO
    com.herwaycabs: INFO
