server:
  port: ${PORT:8085}

spring:
  application:
    name: kyc-service

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://herwaycabs-discovery.onrender.com/eureka/}

  instance:
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.herwaycabs: INFO
    org.hibernate: INFO